stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "."
  TF_PLAN: "$CI_PROJECT_DIR/tfplan"

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -sSL https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip -o terraform.zip
  - unzip terraform.zip -d /usr/local/bin
  - terraform --version
  - terraform init -chdir=$TF_ROOT

validate:
  stage: validate
  image: google/cloud-sdk:latest
  script:
    - terraform validate -chdir=$TF_ROOT

plan:
  stage: plan
  image: google/cloud-sdk:latest
  script:
    - terraform plan -out=$TF_PLAN -chdir=$TF_ROOT
  artifacts:
    paths:
      - $TF_PLAN

apply:
  stage: apply
  image: google/cloud-sdk:latest
  script:
    -


