apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: zhyldyz.site
  dnsNames:
  - zhyldyz.site
