apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default
type: Opaque
data:
  hostname: MzQuMTM1LjIzMi4xNjQ=
  username: cG9zdGdyZXM=
  password: MTIzNA==
  database: cG9zdGdyZXM=
