# Default values for my-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/reference-node-434715-i6/backend-app
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 80  # Добавляем targetPort для соответствия порту контейнера

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # Запросы и лимиты ресурсов для контейнеров можно добавить здесь, если потребуется.

nodeSelector: {}
  # Настройки для выбора узлов для размещения Pod'ов.

tolerations: {}
  # Настройки для обеспечения размещения Pod'ов на узлах с определенными терпимостями.

affinity: {}
  # Конфигурация аффинности для управления размещением Pod'ов на узлах.

  