stages:
  - build
  - deploy

variables:
  IMAGE_NAME_FRONT: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/awesome_cats_front"
  IMAGE_NAME_BACK: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/awesome_cats_back"
  TAG_NAME: "latest"
  TF_VERSION: "1.9.3"

.build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache curl unzip
    - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /usr/local/bin/
    - terraform --version
  script:
    # Build and push for awesome_cats_front
    - docker build -t $IMAGE_NAME_FRONT:$TAG_NAME ./awesome_cats_front
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $IMAGE_NAME_FRONT:$TAG_NAME

    # Build and push for awesome_cats_back
    - docker build -t $IMAGE_NAME_BACK:$TAG_NAME ./awesome_cats_back
    - docker push $IMAGE_NAME_BACK:$TAG_NAME
  only:
    - main

.deploy:
  stage: deploy
  script:
    - echo "Deploy stage. Add your deploy scripts here."
  only:
    - main

build:
  extends: .build

deploy:
  extends: .deploy
