stages:
  - build
  - deploy

variables:
  IMAGE_NAME_FRONT: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/awesome_cats_front"
  IMAGE_NAME_BACK: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/awesome_cats_back"
  TAG_NAME: "latest"

# Build stage for Docker images
build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache curl unzip
  script:
    # Build and push frontend image
    - docker build -t $IMAGE_NAME_FRONT:$TAG_NAME ./awesome_cats_front
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $IMAGE_NAME_FRONT:$TAG_NAME

    # Build and push backend image
    - docker build -t $IMAGE_NAME_BACK:$TAG_NAME ./awesome_cats_back
    - docker push $IMAGE_NAME_BACK:$TAG_NAME
  only:
    - main

# Deploy stage placeholder
deploy:
  stage: deploy
  script:
    - echo "Deploy stage. Add your deploy scripts here."
  only:
    - main
